name: gym_rat
description: "나만의 헬스 기록 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: 3.1.1
  intl: 0.19.0
  drift: 2.13.0
  path_provider: 2.1.1
  path: 1.9.0
  get_it: 7.6.4
  dio: 5.3.3
  provider: 6.0.5
  uuid: 4.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: 2.13.0
  build_runner: 2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  #    - assets/images
  - assets/json/exercises.json
  - assets/json/info.json
  fonts:
  - family: NanumGothic
    fonts:
    - asset: assets/fonts/NanumGothic-Bold.ttf
    - asset: assets/fonts/NanumGothic-ExtraBold.ttf
    - asset: assets/fonts/NanumGothic-Regular.ttf
